default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: microservices

development:
  <<: *default
  username: postgres
  host: localhost
  database: microservices

production:
  <<: *default
  username: <%= ENV['DB_USERNAME']%>
  password: <%= ENV['DB_PASSWORD']%>
  host: <%= ENV['DB_HOST']%>
  database: ads_microservice_production

test:
  <<: *default
  username: postgres
  host: localhost
  database: microservices_test
